server:
  port: 7000

spring:
  main:
    banner-mode: off
  application:
    name: author
  profiles:
    active: local

management:
  server:
    port: 7001
  endpoints:
    web:
      exposure:
        include: ["*"]

---

spring:
  config:
    activate:
      on-profile: local
    import: "consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: yaml
        data-key: config
