server:
  port: 7010
spring:
  main:
    banner-mode: off
  application:
    name: book
  profiles:
    active: local

management:
  server:
    port: 7011
  endpoints:
    web:
      exposure:
        include: ["*"]
---
spring:
  config:
    activate:
      on-profile: local
    import: "optional:consul:"
  liquibase:
    drop-first: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/author
    username: postgres
    password: 1111
---
spring:
  config:
    activate:
      on-profile: consul
    import: "consul:"
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: yaml
        data-key: config